from __future__ import annotations

from typing import Any

from hyperparameters._common import get_preset


PRESETS: dict[str, dict[str, Any]] = {
    "dm_control/cheetah/run": {
        "num_envs": 1,
        "total_steps": 1_000_000,
        "eval_interval": 10_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (526, 526, 256),
        "rollout_steps": 1024,
        "update_epochs": 4,
        "minibatch_size": 256,
        "policy_lr": 2e-4,
        "value_lr": 3e-4,
        "clip_ratio": 0.25,
        "ent_coef": 1e-4,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "vf_coef": 1.0,
        "max_grad_norm": 0.5,
        "target_kl": 0.02,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "dm_control/humanoid/run": {
        "num_envs": 1,
        "total_steps": 1_000_000,
        "eval_interval": 10_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (526, 526, 256),
        "rollout_steps": 8192,
        "update_epochs": 12,
        "minibatch_size": 512,
        "policy_lr": 1e-4,
        "value_lr": 2e-5,
        "clip_ratio": 0.15,
        "ent_coef": 3e-4,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "vf_coef": 0.5,
        "max_grad_norm": 0.5,
        "target_kl": 0.02,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "dm_control/humanoid/walk": {
        "num_envs": 1,
        "total_steps": 1_000_000,
        "eval_interval": 10_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (526, 526, 256),
        "rollout_steps": 1024,
        "update_epochs": 2,
        "minibatch_size": 256,
        "policy_lr": 2e-4,
        "value_lr": 5e-5,
        "clip_ratio": 0.2,
        "ent_coef": 5e-4,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "vf_coef": 0.5,
        "max_grad_norm": 0.5,
        "target_kl": 0.02,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "dm_control/walker/walk": {
        "num_envs": 4,
        "total_steps": 1_000_000,
        "eval_interval": 10_000,
        "save_interval": 10_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (526, 526, 256),
        "rollout_steps": 1024,
        "update_epochs": 4,
        "minibatch_size": 128,
        "policy_lr": 2e-4,
        "value_lr": 1e-4,
        "clip_ratio": 0.2,
        "ent_coef": 1e-4,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "vf_coef": 0.5,
        "max_grad_norm": 0.5,
        "target_kl": 0.02,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "dm_control/walker/run": {
        "num_envs": 4,
        "total_steps": 1_000_000,
        "eval_interval": 10_000,
        "save_interval": 10_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (526, 526, 256),
        "rollout_steps": 1024,
        "update_epochs": 4,
        "minibatch_size": 256,
        "policy_lr": 2e-4,
        "value_lr": 1e-4,
        "clip_ratio": 0.2,
        "ent_coef": 1e-4,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "vf_coef": 0.5,
        "max_grad_norm": 0.5,
        "target_kl": 0.02,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "dm_control/cartpole/swingup": {
        "num_envs": 2,
        "total_steps": 1_000_000,
        "eval_interval": 10_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (526, 526, 256),
        "rollout_steps": 512,
        "update_epochs": 3,
        "minibatch_size": 128,
        "policy_lr": 3e-4,
        "value_lr": 1e-4,
        "clip_ratio": 0.2,
        "ent_coef": 1e-3,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "vf_coef": 0.5,
        "max_grad_norm": 0.5,
        "target_kl": 0.02,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": False,
    },
    "Humanoid-v5": {
        "num_envs": 1,
        "total_steps": 1_000_000,
        "eval_interval": 10_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (526, 526, 256),
        "rollout_steps": 8192,
        "update_epochs": 12,
        "minibatch_size": 512,
        "policy_lr": 1e-4,
        "value_lr": 2e-5,
        "clip_ratio": 0.15,
        "ent_coef": 3e-4,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "vf_coef": 0.5,
        "max_grad_norm": 0.5,
        "target_kl": 0.02,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "HalfCheetah-v5": {
        "num_envs": 1,
        "total_steps": 2_000_000,
        "eval_interval": 10_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (526, 526, 256),
        "rollout_steps": 1024,
        "update_epochs": 10,
        "minibatch_size": 128,
        "policy_lr": 2e-4,
        "value_lr": 3e-5,
        "clip_ratio": 0.15,
        "ent_coef": 1e-4,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "vf_coef": 0.5,
        "max_grad_norm": 1.0,
        "target_kl": 0.02,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "Ant-v5": {
        "num_envs": 1,
        "total_steps": 1_000_000,
        "eval_interval": 10_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (526, 526, 256),
        "rollout_steps": 8192,
        "update_epochs": 12,
        "minibatch_size": 512,
        "policy_lr": 1e-4,
        "value_lr": 2e-5,
        "clip_ratio": 0.15,
        "ent_coef": 3e-4,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "vf_coef": 0.5,
        "max_grad_norm": 0.5,
        "target_kl": 0.02,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "Walker2d-v5": {
        "num_envs": 1,
        "total_steps": 1_000_000,
        "eval_interval": 10_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (526, 526, 256),
        "rollout_steps": 8192,
        "update_epochs": 12,
        "minibatch_size": 512,
        "policy_lr": 1e-4,
        "value_lr": 2e-5,
        "clip_ratio": 0.15,
        "ent_coef": 3e-4,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "vf_coef": 0.5,
        "max_grad_norm": 1.0,
        "target_kl": 0.02,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
}


def get(env_id: str) -> dict[str, Any]:
    return get_preset(
        env_id=env_id,
        presets=PRESETS,
        algorithm_name="PPO",
        defaults={"optimizer_type": "adam", "sgd_momentum": 0.9},
    )
