from __future__ import annotations

from typing import Any

from hyperparameters._common import get_preset


PRESETS: dict[str, dict[str, Any]] = {
    "dm_control/cheetah/run": {
        "num_envs": 1,
        "total_steps": 500_000,
        "eval_interval": 10_000,
        "save_interval": 500_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 2048,
        "update_epochs": 10,
        "minibatch_size": 32,
        "policy_lr": 2e-4,
        "value_lr": 1e-4,
        "clip_ratio": 0.2,
        "ent_coef": 0,
        "gamma": 0.98,
        "gae_lambda": 0.92,
        "vf_coef": 0.5,
        "max_grad_norm": 0.8,
        "target_kl": 0,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "dm_control/humanoid/run": {
        "num_envs": 1,
        "total_steps": 500_000,
        "eval_interval": 10_000,
        "save_interval": 500_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 2048,
        "update_epochs": 10,
        "minibatch_size": 32,
        "policy_lr": 2e-4,
        "value_lr": 1e-4,
        "clip_ratio": 0.2,
        "ent_coef": 0,
        "gamma": 0.98,
        "gae_lambda": 0.92,
        "vf_coef": 0.5,
        "max_grad_norm": 0.8,
        "target_kl": 0,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "dm_control/humanoid/walk": {
        "num_envs": 1,
        "total_steps": 500_000,
        "eval_interval": 10_000,
        "save_interval": 500_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 2048,
        "update_epochs": 10,
        "minibatch_size": 32,
        "policy_lr": 2e-4,
        "value_lr": 1e-4,
        "clip_ratio": 0.2,
        "ent_coef": 0,
        "gamma": 0.98,
        "gae_lambda": 0.92,
        "vf_coef": 0.5,
        "max_grad_norm": 0.8,
        "target_kl": 0,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "dm_control/walker/walk": {
        "num_envs": 4,
        "total_steps": 500_000,
        "eval_interval": 10_000,
        "save_interval": 500_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 2048,
        "update_epochs": 10,
        "minibatch_size": 32,
        "policy_lr": 2e-4,
        "value_lr": 1e-4,
        "clip_ratio": 0.2,
        "ent_coef": 0,
        "gamma": 0.98,
        "gae_lambda": 0.92,
        "vf_coef": 0.5,
        "max_grad_norm": 0.8,
        "target_kl": 0,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "dm_control/walker/run": {
        "num_envs": 4,
        "total_steps": 500_000,
        "eval_interval": 10_000,
        "save_interval": 500_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 2048,
        "update_epochs": 10,
        "minibatch_size": 32,
        "policy_lr": 2e-4,
        "value_lr": 1e-4,
        "clip_ratio": 0.2,
        "ent_coef": 0,
        "gamma": 0.98,
        "gae_lambda": 0.92,
        "vf_coef": 0.5,
        "max_grad_norm": 0.8,
        "target_kl": 0,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "dm_control/cartpole/swingup": {
        "num_envs": 2,
        "total_steps": 500_000,
        "eval_interval": 10_000,
        "save_interval": 500_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 2048,
        "update_epochs": 10,
        "minibatch_size": 32,
        "policy_lr": 2e-4,
        "value_lr": 1e-4,
        "clip_ratio": 0.2,
        "ent_coef": 0,
        "gamma": 0.98,
        "gae_lambda": 0.92,
        "vf_coef": 0.5,
        "max_grad_norm": 0.8,
        "target_kl": 0,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "Humanoid-v5": {
        "num_envs": 1,
        "total_steps": 500_000,
        "eval_interval": 10_000,
        "save_interval": 500_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 2048,
        "update_epochs": 10,
        "minibatch_size": 32,
        "policy_lr": 2e-4,
        "value_lr": 1e-4,
        "clip_ratio": 0.2,
        "ent_coef": 0,
        "gamma": 0.98,
        "gae_lambda": 0.92,
        "vf_coef": 0.5,
        "max_grad_norm": 0.8,
        "target_kl": 0,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "HalfCheetah-v5": {
        "num_envs": 1,
        "total_steps": 500_000,
        "eval_interval": 10_000,
        "save_interval": 500_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 2048,
        "update_epochs": 10,
        "minibatch_size": 32,
        "policy_lr": 2e-4,
        "value_lr": 1e-4,
        "clip_ratio": 0.2,
        "ent_coef": 0,
        "gamma": 0.98,
        "gae_lambda": 0.92,
        "vf_coef": 0.5,
        "max_grad_norm": 0.8,
        "target_kl": 0,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "Ant-v5": {
        "num_envs": 1,
        "total_steps": 500_000,
        "eval_interval": 10_000,
        "save_interval": 500_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 2048,
        "update_epochs": 10,
        "minibatch_size": 32,
        "policy_lr": 2e-4,
        "value_lr": 1e-4,
        "clip_ratio": 0.2,
        "ent_coef": 0,
        "gamma": 0.98,
        "gae_lambda": 0.92,
        "vf_coef": 0.5,
        "max_grad_norm": 0.8,
        "target_kl": 0,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
    "Walker2d-v5": {
        "num_envs": 1,
        "total_steps": 500_000,
        "eval_interval": 10_000,
        "save_interval": 500_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 2048,
        "update_epochs": 10,
        "minibatch_size": 32,
        "policy_lr": 2e-4,
        "value_lr": 1e-4,
        "clip_ratio": 0.2,
        "ent_coef": 0,
        "gamma": 0.98,
        "gae_lambda": 0.92,
        "vf_coef": 0.5,
        "max_grad_norm": 0.8,
        "target_kl": 0,
        "norm_adv": True,
        "clip_vloss": True,
        "anneal_lr": True,
        "normalize_obs": True,
    },
}


def get(env_id: str) -> dict[str, Any]:
    return get_preset(
        env_id=env_id,
        presets=PRESETS,
        algorithm_name="PPO",
        defaults={"optimizer_type": "adam", "sgd_momentum": 0.9},
    )
