from __future__ import annotations

from typing import Any

from hyperparameters._common import get_preset


PRESETS: dict[str, dict[str, Any]] = {
    "dm_control/cheetah/run": {
        "num_envs": 1,
        "total_steps": 3_000_000,
        "eval_interval": 10_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 1024,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "target_kl": 0.02,
        "cg_iters": 10,
        "cg_damping": 0.1,
        "backtrack_coeff": 0.8,
        "backtrack_iters": 10,
        "value_lr": 1e-3,
        "value_epochs": 10,
        "value_minibatch_size": 256,
        "max_grad_norm": 0.5,
        "normalize_advantages": True,
        "normalize_obs": True,
    },
    "dm_control/humanoid/run": {
        "num_envs": 1,
        "total_steps": 1_000_000,
        "eval_interval": 25_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 8192,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "target_kl": 0.01,
        "cg_iters": 10,
        "cg_damping": 0.1,
        "backtrack_coeff": 0.8,
        "backtrack_iters": 10,
        "value_lr": 3e-4,
        "value_epochs": 20,
        "value_minibatch_size": 1024,
        "max_grad_norm": 0.5,
        "normalize_advantages": True,
        "normalize_obs": True,
    },
    "dm_control/humanoid/walk": {
        "num_envs": 1,
        "total_steps": 1_000_000,
        "eval_interval": 50_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 1024,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "target_kl": 0.015,
        "cg_iters": 10,
        "cg_damping": 0.1,
        "backtrack_coeff": 0.8,
        "backtrack_iters": 10,
        "value_lr": 3e-4,
        "value_epochs": 15,
        "value_minibatch_size": 512,
        "max_grad_norm": 0.5,
        "normalize_advantages": True,
        "normalize_obs": True,
    },
    "dm_control/walker/walk": {
        "num_envs": 4,
        "total_steps": 1_000_000,
        "eval_interval": 15_000,
        "save_interval": 50_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 1024,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "target_kl": 0.015,
        "cg_iters": 10,
        "cg_damping": 0.1,
        "backtrack_coeff": 0.8,
        "backtrack_iters": 10,
        "value_lr": 3e-4,
        "value_epochs": 10,
        "value_minibatch_size": 512,
        "max_grad_norm": 0.5,
        "normalize_advantages": True,
        "normalize_obs": True,
    },
    "dm_control/walker/run": {
        "num_envs": 4,
        "total_steps": 1_000_000,
        "eval_interval": 15_000,
        "save_interval": 50_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 1024,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "target_kl": 0.015,
        "cg_iters": 10,
        "cg_damping": 0.1,
        "backtrack_coeff": 0.8,
        "backtrack_iters": 10,
        "value_lr": 3e-4,
        "value_epochs": 15,
        "value_minibatch_size": 1024,
        "max_grad_norm": 0.5,
        "normalize_advantages": True,
        "normalize_obs": True,
    },
    "dm_control/cartpole/swingup": {
        "num_envs": 2,
        "total_steps": 1_000_000,
        "eval_interval": 50_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 512,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "target_kl": 0.02,
        "cg_iters": 10,
        "cg_damping": 0.1,
        "backtrack_coeff": 0.8,
        "backtrack_iters": 10,
        "value_lr": 1e-3,
        "value_epochs": 10,
        "value_minibatch_size": 256,
        "max_grad_norm": 0.5,
        "normalize_advantages": True,
        "normalize_obs": False,
    },
    "Humanoid-v5": {
        "num_envs": 1,
        "total_steps": 1_000_000,
        "eval_interval": 10_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 8192,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "target_kl": 0.01,
        "cg_iters": 10,
        "cg_damping": 0.1,
        "backtrack_coeff": 0.8,
        "backtrack_iters": 10,
        "value_lr": 3e-4,
        "value_epochs": 20,
        "value_minibatch_size": 1024,
        "max_grad_norm": 0.5,
        "normalize_advantages": True,
        "normalize_obs": True,
    },
    "HalfCheetah-v5": {
        "num_envs": 1,
        "total_steps": 1_000_000,
        "eval_interval": 10_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 8192,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "target_kl": 0.01,
        "cg_iters": 10,
        "cg_damping": 0.1,
        "backtrack_coeff": 0.8,
        "backtrack_iters": 10,
        "value_lr": 3e-4,
        "value_epochs": 10,
        "value_minibatch_size": 1024,
        "max_grad_norm": 0.5,
        "normalize_advantages": True,
        "normalize_obs": True,
    },
    "Ant-v5": {
        "num_envs": 1,
        "total_steps": 1_000_000,
        "eval_interval": 10_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 8192,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "target_kl": 0.01,
        "cg_iters": 10,
        "cg_damping": 0.1,
        "backtrack_coeff": 0.8,
        "backtrack_iters": 10,
        "value_lr": 3e-4,
        "value_epochs": 10,
        "value_minibatch_size": 1024,
        "max_grad_norm": 0.5,
        "normalize_advantages": True,
        "normalize_obs": True,
    },
    "Walker2d-v5": {
        "num_envs": 1,
        "total_steps": 1_000_000,
        "eval_interval": 10_000,
        "save_interval": 1_000_000,
        "policy_layer_sizes": (256, 256, 256),
        "critic_layer_sizes": (512, 512, 256),
        "rollout_steps": 8192,
        "gamma": 0.99,
        "gae_lambda": 0.95,
        "target_kl": 0.01,
        "cg_iters": 10,
        "cg_damping": 0.1,
        "backtrack_coeff": 0.8,
        "backtrack_iters": 10,
        "value_lr": 3e-4,
        "value_epochs": 10,
        "value_minibatch_size": 1024,
        "max_grad_norm": 0.5,
        "normalize_advantages": True,
        "normalize_obs": True,
    },
}


def get(env_id: str) -> dict[str, Any]:
    return get_preset(
        env_id=env_id,
        presets=PRESETS,
        algorithm_name="TRPO",
        defaults={"optimizer_type": "adam", "sgd_momentum": 0.9},
    )
